spring.application.name=toilet

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

toilet.data.path=classpath:seoultoilet.json

kakao.api.key=8a0a040c698bc28e08603728a9ff14cb

