spring.application.name=toilet

#spring.datasource.url=jdbc:h2:tcp://localhost/~/test
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# ?? X
spring.datasource.url=jdbc:mysql://localhost:3306/toiletreview?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=publictoiletmap
spring.datasource.password=1111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# AWS ??(ec2+rds)
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://publictoiletmap.cpuc80i2iv72.ap-northeast-2.rds.amazonaws.com:3306/toiletmap?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
#spring.datasource.username=admin
#spring.datasource.password=didwlsdn


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

toilet.data.path=classpath:seoultoilet.json

kakao.api.key=8a0a040c698bc28e08603728a9ff14cb
