-- 화장실
CREATE TABLE IF NOT EXISTS toilet (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conts_name    VARCHAR(255),
    addr_new      VARCHAR(255),
    addr_old      VARCHAR(255),
    coord_x       DOUBLE,           -- 경도 (x)
    coord_y       DOUBLE            -- 위도 (y)
);

-- 리뷰
CREATE TABLE IF NOT EXISTS review (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    toilet_id     BIGINT NOT NULL,
    rating        INT    NOT NULL,
    comment       VARCHAR(1000),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_review_toilet
      FOREIGN KEY (toilet_id) REFERENCES toilet(id)

    CONSTRAINT chk_review_rating
        CHECK (rating BETWEEN 1 AND 5)
);

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_review_toilet  ON review(toilet_id);
CREATE INDEX IF NOT EXISTS idx_toilet_coord   ON toilet(coord_y, coord_x);
