-- 화장실
CREATE TABLE IF NOT EXISTS toilet (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conts_name    VARCHAR(255),
    addr_new      VARCHAR(255),
    addr_old      VARCHAR(255),
    coord_x       DOUBLE,           -- 경도(x)
    coord_y       DOUBLE,           -- 위도(y)
    value04       VARCHAR(64),      -- 남/여/장애/기타
    value05       VARCHAR(64),
    external_id   VARCHAR(64)       -- 업서트 자연키(자연키 해시/고유값 저장)(동일 데이터 중복 삽입 않고 갱신)
);

-- external_id 유니크 인덱스(동일 화장실 데이터 중복 저장 방지)
CREATE UNIQUE INDEX IF NOT EXISTS ux_toilet_external_id ON toilet(external_id);

-- 리뷰
CREATE TABLE IF NOT EXISTS review (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    toilet_id     BIGINT NOT NULL,
    rating        INT    NOT NULL,
    comment       VARCHAR(1000),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_review_rating CHECK (rating BETWEEN 1 AND 5)
);

-- FK 재정의
ALTER TABLE review DROP CONSTRAINT IF EXISTS fk_review_toilet;
ALTER TABLE review ADD CONSTRAINT fk_review_toilet
    FOREIGN KEY (toilet_id) REFERENCES toilet(id) ON DELETE CASCADE;

-- 인덱스 최적화(특정 화장실, 최신 순, 좌표)
CREATE INDEX IF NOT EXISTS idx_review_toilet     ON review(toilet_id);
CREATE INDEX IF NOT EXISTS idx_review_created_at ON review(created_at);
CREATE INDEX IF NOT EXISTS idx_toilet_coord      ON toilet(coord_y, coord_x);
